@startuml

Class Application{


}
Class Item{
    String description;
    String date;

    +getDescription()
    +setDescription()
    +getDate()
    +setDate()

}

Class TodoItemManager{
    String date
    String description

    +addTask(String date,String description)
    +deleteTask(int index)
    +clearList()
    +markComplete(int index)
    -displayAll()
    -displayComplete()
    -displayIncomplete()
    -saveList()
    -loadList()


    -displayAll()
    -displayComplete()
    -displayIncomplete()
}


Application --> TodoItemManager

TodoItemManager --> Item
@enduml