@startuml

Class Application{


}
Class Item{
    String description;
    String date;

    +getDescription()
    +setDescription()
    +getDate()
    +setDate()

}

Class TodoItemManager{
    String date
    String description

    +addTask(String date,String description)
    +deleteTask(int index)
    +clearList()
    +saveList()
    +loadList()
}


Application --> TodoItemManager

TodoItemManager --> Item
@enduml